dist: xenial
language: ruby
sudo: false

cache:
  bundler: true
  directories:
    - /home/travis/.rvm/gems

rvm:
  - 2.6

env:
  matrix:
    - RAILS_VERSION=v6.0.0 GEM=activerecord:mysql2
    - RAILS_VERSION=v6.0.0 GEM=activerecord:sqlite3
    - RAILS_VERSION=v6.0.0 GEM=activerecord:postgresql
    - RAILS_VERSION=v6.0.2.1 GEM=activerecord:mysql2
    - RAILS_VERSION=v6.0.2.1 GEM=activerecord:sqlite3
    - RAILS_VERSION=v6.0.2.1 GEM=activerecord:postgresql
    - RAILS_VERSION=v6.0.3.2 GEM=activerecord:mysql2
    - RAILS_VERSION=v6.0.3.2 GEM=activerecord:sqlite3
    - RAILS_VERSION=v6.0.3.2 GEM=activerecord:postgresql

services:
  - mysql
addons:
  postgresql: "10"

before_install:
  - unset BUNDLE_GEMFILE
  - gem update --system
  - gem update bundler
  - gem install bundler --version 1.17.3

install:
  - git clone --branch $RAILS_VERSION https://github.com/rails/rails.git ~/build/rails

before_script:
  - sed -i "s/t.warning = true/t.warning = false/g" Rakefile
  - pushd ~/build/rails
  - git status
  - sed -i "s/Gem.ruby, '-w'/Gem.ruby, '-w0'/" ~/build/rails/activerecord/Rakefile
  - sed -i "s/t.warning = true/t.warning = false/g" ~/build/rails/activerecord/Rakefile
  - sed -i "/require 'support\/connection'/a \$LOAD_PATH.unshift\(File.expand_path\('~\/build\/malomalo\/sunstone\/lib'\)\)\nrequire 'sunstone'" ~/build/rails/activerecord/test/cases/helper.rb
  - cat ~/build/rails/Gemfile
  - rm ~/build/rails/Gemfile.lock
  - "sed -i \"/# Active Record./a gem 'sunstone', path: File.expand_path\\('~\\/build\\/malomalo\\/sunstone'\\)\" ~/build/rails/Gemfile"
  - cat ~/build/rails/Gemfile
  - bundle update --jobs=3 --retry=3
  - popd
  - bundle install --jobs=3 --retry=3

script:
  - bundle exec rake test
  - cd ~/build/rails && ci/travis.rb
